import type { DocSection, DocPage } from "../types";

const packages: DocPage = {
  slug: "packages",
  title: "Packages & Lockfile",
  description:
    "Project manifests, canonical lockfiles, local dependencies, and reproducible dependency commands.",
  source: "docs/PACKAGE_EN.md",
  markdown: `A Zap project stores its package manifest in \`zap.toml\` at the project root. The native runtime validates the manifest with \`zap check\`, validates the entry source, and — when dependencies are declared — requires a canonical \`zap.lock\` file.

## Minimal manifest

\`\`\`toml
[package]
name = "hello-app"
version = "0.1.0"
main = "main.zp"
\`\`\`

If \`main\` is omitted, Zap uses \`main.zp\` as the default entry file.

## Declaring dependencies

Dependencies are declared in a \`[dependencies]\` table. A dependency may use a deterministic version requirement or a local path specification. Dependency entries are sorted by package name when the lockfile is generated.

\`\`\`toml
[package]
name = "hello-app"
version = "0.1.0"
main = "main.zp"

[dependencies]
web = "0.3"
json-tools = "1.2"
local-lib = { path = "../local-lib" }
\`\`\`

## Canonical lockfile

\`\`\`bash
zap lock
zap lock path/to/project
\`\`\`

Zap writes a canonical \`zap.lock\` containing the lockfile version, package identity, and dependencies in lexicographic order. The file is generated output and should be committed with the project so that all environments validate the same dependency requirements.

\`\`\`toml
# This file is generated by Zap. Do not edit manually.
lockfile_version = 1

[package]
name = "hello-app"
version = "0.1.0"

[dependencies]
json-tools = "1.2"
local-lib = { path = "../local-lib" }
web = "0.3"
\`\`\`

\`zap check\`, \`zap build\`, and other project validation paths reject a project when a dependency lockfile is missing, stale, or not in canonical form. Regenerate it with \`zap lock\` after changing \`zap.toml\` dependencies or the package version.

## Lockfile version 2

When \`ZAP_REGISTRY_INDEX\` is configured and the manifest contains registry dependencies, \`zap lock\` and \`zap update\` emit lockfile version 2. In addition to the manifest requirements, the v2 file contains a deterministic \`[resolved]\` section that pins each selected registry package by name, version, source, and SHA-256 checksum:

\`\`\`toml
lockfile_version = 2

[package]
name = "hello-app"
version = "0.1.0"

[dependencies]
web = "0.3"

[resolved]
web.version = "0.3.1"
web.source = "file://web.pkg"
web.checksum = "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
\`\`\`

\`zap install\` treats v2 resolved entries as exact pins. It re-resolves the configured registry index, compares the complete graph and checksums with the lockfile, and verifies every cached artifact. A changed source, version, dependency graph, or checksum requires \`zap update\`; an offline install succeeds only when every pinned artifact is already cached and still matches its checksum. Existing v1 lockfiles remain readable for compatibility.

> Deterministic behavior means that the same manifest and registry index produce byte-for-byte identical lockfile content, independent of filesystem enumeration order.

## Recommended layout

\`\`\`text
hello-app/
├── zap.toml
├── zap.lock
├── main.zp
├── modules/
│   └── math.zp
└── lib/
    └── text.zp
\`\`\`

Local \`use "math"\` or \`use "math.zp"\` imports are searched relative to the main file, then \`modules/\`, and then \`lib/\`. A local path is resolved relative to the consuming project. The referenced directory must exist and contain a \`zap.toml\` with package \`name\` and \`version\` metadata.

Local dependencies are recursively traversed in lexicographic depth-first order, so nested local packages are validated before the command succeeds. If a canonical package path appears again on the active traversal stack, Zap rejects the graph with a deterministic diagnostic such as \`dependency cycle detected: left -> right -> left\`.

## Registry-ready package metadata

The \`[package]\` table accepts optional metadata for future registry publication:

\`\`\`toml
[package]
name = "hello-app"
version = "0.1.0"
description = "A small Zap application"
authors = ["Zap Team"]
license = "MIT"
repository = "https://github.com/hidecard/zap"
checksum = "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
\`\`\`

\`description\`, \`license\`, and \`repository\` must be non-empty quoted strings. \`authors\` may be a non-empty quoted string or array. When present, \`checksum\` must be exactly 64 hexadecimal characters representing a SHA-256 digest.

## Adding, installing, updating

\`\`\`bash
zap add json-tools 1.2
zap install
zap update
\`\`\`

- \`zap add <name> <version> [dir]\` — update the manifest without hand-editing the dependency table. Rejects duplicate names, keeps entries in lexicographic order, and removes the existing \`zap.lock\`.
- \`zap install [dir]\` — **validation-only**. Verifies the existing manifest and lockfile (and registry cache when \`ZAP_REGISTRY_INDEX\` is set) without changing dependency requirements. CI-friendly.
- \`zap update [dir]\` — regenerates the canonical lockfile. Recursively resolves registry requirements and verifies cached/downloaded package checksums.

For example, a project whose direct dependency \`appdep\` resolves to transitive package \`leaf\` reports:

\`\`\`text
installed 2 locked dependencies: appdep@1.0.0, leaf@1.0.0
\`\`\`

## Project commands

| Command | Purpose |
|---|---|
| \`zap check\` | Validate the manifest, lockfile, entry file, and static source checks |
| \`zap lock\` | Generate or regenerate the canonical \`zap.lock\` |
| \`zap lock-migrate [dir]\` | Explicitly migrate a legacy lockfile when registry metadata is available |
| \`zap add <name> <version> [dir]\` | Add a deterministic version dependency and invalidate the lockfile |
| \`zap install [dir]\` | Validate the existing manifest and lockfile without changing them |
| \`zap update [dir]\` | Regenerate the canonical lockfile and validate the local dependency graph |
| \`zap build\` | Validate and prepare a Zap project |
| \`zap test\` | Run project test files |
| \`zap fmt main.zp\` | Format a Zap source file |
`,
};

const registry: DocPage = {
  slug: "registry",
  title: "Registry",
  description:
    "Dependency-free JSON index, content-addressed cache, SHA-256 integrity, offline reuse, and authenticated loopback service.",
  source: "docs/PACKAGE_EN.md",
  markdown: `## JSON index

Zap provides a dependency-free registry foundation through a JSON index and a content-addressed cache. The index is intentionally explicit and deterministic:

\`\`\`json
{
  "packages": [
    {
      "name": "demo",
      "version": "1.0.0",
      "source": "file://demo.pkg",
      "checksum": "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef",
      "dependencies": {
        "http-core": "^1.2.0"
      }
    }
  ]
}
\`\`\`

Validate an index with \`zap registry check path/to/index.json\`. Package selection requires an **exact** \`name\` and \`version\` match; ambiguous or missing entries are rejected. A file-backed source is resolved relative to the index file, copied into the cache, and verified against the declared SHA-256 checksum before it is accepted.

The cache layout is \`.zap/cache/<name>/<version>/<checksum>.pkg\`, unless \`ZAP_CACHE_DIR\` specifies another root.

## Project dependency resolution

Set \`ZAP_REGISTRY_INDEX\` to a local path, \`file://\` URL, or HTTPS URL. Use \`zap registry fetch <index-url>\` to validate a remote index before project resolution. \`zap install\` verifies existing cache entries and downloads missing artifacts from local or HTTPS sources. \`zap update\` performs the same registry validation before rewriting the canonical lockfile.

Registry package records may include a \`dependencies\` object whose values are version requirements. Zap resolves direct and transitive registry dependencies in lexical order, selects the highest compatible version, and caches/verifies every selected package.

## Offline mode

Set \`ZAP_OFFLINE=1\` to prohibit new downloads; offline commands succeed only when every transitive registry dependency is already cached and its checksum still matches.

- Missing transitive artifacts report \`registry package is not cached in offline mode: <name> <version>\`.
- A tampered cached artifact reports \`cached package checksum mismatch for <name> <version>\`.
- Incomplete or non-canonical v2 lockfiles are rejected with \`zap.lock: out of date or non-canonical; run \`zap lock\` to regenerate it\`.

Plain HTTP is rejected unless \`ZAP_ALLOW_INSECURE_HTTP=1\` is explicitly set for local fixtures.

## Transport safety

Remote fetches accept ordinary partial socket reads and HTTP chunked transfer bodies, cap a response at 16 MiB, reject invalid or truncated \`Content-Length\` bodies before JSON/package acceptance, and normalize a slow response read to \`registry response read timed out\` under the five-second client transport deadline.

- Non-2xx index and artifact responses are normalized to \`registry HTTP fetch failed with HTTP <status>\`.
- Malformed JSON is reported as \`registry index JSON is invalid: <details>\`.
- Non-2xx publishing responses are reported as \`registry publish failed with HTTP <status>\`.

## Publishing

Remote publishing sends a checksum-verified package archive to an HTTPS endpoint using stable \`X-Zap-Package-*\` headers. Set \`ZAP_REGISTRY_TOKEN\` for bearer authentication and run:

\`\`\`bash
zap registry publish https://registry.example/publish ./demo.pkg demo 1.0.0 <sha256>
\`\`\`

The archive is hashed **before** any network request, so a checksum mismatch cannot publish.

## Local registry service

For local integration and controlled development environments, \`zap registry serve\` starts a loopback-only HTTP service around the signed-index persistence boundary:

\`\`\`bash
zap registry serve <root> [bind]
\`\`\`

The service:

- Requires \`ZAP_REGISTRY_TOKEN\` for bearer authentication and \`ZAP_REGISTRY_SIGNING_SECRET\` for signed-index persistence.
- Bounds request headers and bodies.
- Serves only safe in-root \`GET\` paths.
- Persists published records atomically.
- Supports managed shutdown.

The service rejects unauthorized, traversal-style, malformed, and oversized requests deterministically. M2-REG-01 transport regressions cover chunked bodies, partial/truncated responses, slow peers, and oversized response declarations.

> Public production deployment, TLS termination, network ingress policy, and external process supervision remain deployment-specific controls. See [Deployment](#deployment).
`,
};

export const packagesSection: { section: DocSection; pages: DocPage[] } = {
  section: {
    id: "packages",
    title: "Packages",
    icon: "Package",
    pages: [
      { slug: "packages", title: "Packages & Lockfile" },
      { slug: "registry", title: "Registry" },
    ],
  },
  pages: [packages, registry],
};
